# Site settings
title: Anirudh K Muralidhar
email: anikamal@iu.edu
description: > # this means to ignore newlines until "baseurl:"
  [Click here to subscribe to my website](https://goo.gl/forms/icZDG9v9eB4BwJlj2)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: anirudhkm
github_username:  anirudhkm
instagram_username: anirudhkm
facebook_username: kmanirudh

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""