# Site settings
title: Anirudh K Muralidhar
email: anirudh796@gmail.com
subscription: https://goo.gl/forms/icZDG9v9eB4BwJlj2
description: > # this means to ignore newlines until "baseurl:"
  We all achieve our dreams 24*7. So the key is focus on what to dream.
  DREAM CONSTRUCTIVE!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: anirudhkm
github_username:  anirudhkm
instagram_username: anirudhkm
facebook_username: kmanirudh

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Data Scientist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
theme: jekyll-theme-cayman